configuration :
    - name : p1 
      ip: localhost
      port : 49996
      clockType: vector
    - name : p2 
      ip : localhost
      port : 42558   
      clockType: vector
    - name : p3  
      ip : localhost 
      port : 50003  
      clockType: vector
    - name : p4
      ip : localhost 
      port : 59877  
      clockType: vector
    - name : p5
      ip : localhost
      port : 59881
      clockType: vector
    - name : p6
      ip : localhost
      port : 59883
      clockType: vector
    - name : p7
      ip : localhost
      port : 59899
      clockType: vector

sendRules :
    - action : delay
      dest : p4
      kind : HTTP_REPLY
      
    - action : delay
      kind : delay
    
    - action : drop
      src : p1  
      dest : p3

    - action : drop
      src : p1
      dest : p2
      kind : Ack

    - action : drop
      src : p1
      kind : Ran

    - action : duplicate
      kind : Request
      dest : p4

    - action : duplicate
      kind : Random
      dest : p2

    - action : delay
      kind : log    
      
receiveRules :    
    - action : drop
      src : p2
      dest : p4
      duplicate : true

    - action : delay
      dest : p4
      kind : HTTP_DELAY
groupList : 
    - groupName : Groupp1
      members :
        - membername : p1
        - membername : p2
        - membername : p3

    - groupName : Groupp2
      members : 
        - membername : p2
        - membername : p4
        - membername : p6

    - groupName : Groupp3
      members : 
        - membername : p3
        - membername : p5
        - membername : p6

    - groupName : Groupp4
      members : 
        - membername : p1
        - membername : p4
        - membername : p5

    - groupName : Groupp5
      members : 
        - membername : p2
        - membername : p5
	- membername : p7

    - groupName : Groupp6
      members : 
        - membername : p1
        - membername : p6
	- membername : p7

    - groupName : Groupp7
      members : 
        - membername : p3
        - membername : p4
	- membername : p7
